### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by sterlingbaldwin** [tjvandal/bcsd-python#2]
My group (climate researchers at LLNL) were looking to implement out own BCSD tool in python, and I came across your repo. Since there's no license file, I'd like to know if the original author would consent to us forking the code and modifying it for our purposes.

**Comment by tjvandal** [comment]
Yes, feel free to fork the code and use as you wish.  I created an MIT license for the repo.

**Comment by sterlingbaldwin** [comment]
Thanks! I'll make sure to attribute you (if you want).
