### ISSUE TITLE
Broken http link to reference document

### ISSUE THREAD

**Issue by sterlingbaldwin** [tjvandal/bcsd-python#3]
https://github.com/tjvandal/bcsd-python/blob/9565b5fcd96ae872cd8076d2a94e13b478c4077e/bias_correct.py#L33

The link referenced here in this documentation isn't valid anymore, the website says that its moved. Do you have a current link to this pdf?

**Comment by sterlingbaldwin** [comment]
Is this the same document? https://esgf.nccs.nasa.gov/esgdoc/NEX-GDDP_Tech_Note_v0.pdf

**Comment by tjvandal** [comment]
Yes, that is the correct document.
